name: Run Newman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Use the forked actions
      - name: Checkout Repository
        uses: VidyaAlaseTraining/checkout@v3  # Your forked version

      - name: Install Node.js
        uses: VidyaAlaseTraining/setup-node@v3  # Your forked version
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Debug File Check
        run: ls -lah

      - name: Run Postman Collection
        run: newman run sample-collection.json -e Weather_API_Testing_postman_environment.json -r json --reporter-json-export results.json
